[build-system]
requires = ["setuptools >= 40.6.0", "wheel", "pip >= 20.1", "requests; sys_platform == 'win32'"]
build-backend = "setuptools.build_meta"

[tool.black]
exclude= """
/(
    salt/ext
  | tests/kitchen
  | templates
)/
"""

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
ensure_newline_before_comments=true
skip="salt/ext,tests/kitchen,templates"
